# Generated by Django 5.0.4 on 2024-04-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitemvariationoption",
            name="variation_option",
        ),
        migrations.AlterField(
            model_name="productitemvariationoption",
            name="product_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productitem",
            ),
        ),
        migrations.AddField(
            model_name="productitemvariationoption",
            name="Variation_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.variationoption",
            ),
        ),
    ]
