# Generated by Django 5.0.4 on 2024-05-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_name_alter_product_slug_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="colour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colour",
                to="products.colour",
            ),
        ),
    ]
