# Generated by Django 5.0.4 on 2024-04-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_remove_productitemvariationoption_variation_option_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="productitemvariationoption",
            old_name="Variation_option",
            new_name="variation_option",
        ),
    ]
