# Generated by Django 5.0.4 on 2024-05-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productvariation_product_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="product_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variation",
                to="products.productitem",
            ),
        ),
    ]
