# Generated by Django 5.0.4 on 2024-04-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_rename_variation_option_productitemvariationoption_variation_option",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="products.category",
            ),
        ),
    ]
