# Generated by Django 5.0.4 on 2024-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvariation_product_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
