# Generated by Django 5.0.4 on 2024-04-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_parent"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productitem",
            table="product_item",
        ),
    ]
