# Generated by Django 5.0.4 on 2024-05-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_review_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.review",
            ),
        ),
    ]
