# Generated by Django 5.0.4 on 2024-05-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_size_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colour",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
