# Generated by Django 5.0.4 on 2024-04-30 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productitem_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variationoption",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variation",
                to="products.variation",
            ),
        ),
    ]
