# Generated by Django 5.0.4 on 2024-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productvariation_colour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
