# Generated by Django 5.0.4 on 2024-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_colour_name_alter_size_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
