# Generated by Django 5.0.4 on 2024-05-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="products",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
