# Generated by Django 5.0.4 on 2024-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0007_alter_review_unique_together_remove_review_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="colour",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
