# Generated by Django 5.0.4 on 2024-05-01 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="product_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_item_image",
                to="products.productitem",
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_item",
                to="products.product",
            ),
        ),
    ]
