# Generated by Django 5.0.4 on 2024-05-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_colour_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("parent", "name")},
        ),
    ]
