# Generated by Django 5.0.4 on 2024-05-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_image_product_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variationoption",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variation_value",
                to="products.variation",
            ),
        ),
    ]
