# Generated by Django 5.0.4 on 2024-05-22 13:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.upload_path
            ),
        ),
    ]
