# Generated by Django 5.0.4 on 2024-04-16 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("be9ddb44-b70c-45ec-a6c5-6022fc2b412d"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a8facca3-55c8-4a75-897c-dcb30f56e181"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9f8fced9-46c3-4f96-9e27-bc971557f877"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
