# Generated by Django 5.0.4 on 2024-04-17 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("75e4a302-77dd-4126-8241-f9f9d97a445c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e9de7ed9-d89b-48b0-88a8-a95f5233637b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("59c2c209-40cc-45d2-b1c8-58b9d9430530"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
