# Generated by Django 5.0.4 on 2024-04-16 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("282f8e1f-e855-4c84-8248-2bc0659721d3"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("55fae193-9044-4646-a26f-56c380070868"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6b25be87-1eb3-47e0-a3f3-295c9c5676c1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
