# Generated by Django 5.0.4 on 2024-04-27 13:00

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_customer_id_buyer_buyer_sellers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellers",
            name="phone_number",
            field=models.CharField(
                unique=True, validators=[accounts.utils.validate_phone_number]
            ),
        ),
    ]
