# Generated by Django 5.0.4 on 2024-04-16 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9756ab4e-42e9-4d09-8d44-01b570d04abb"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7c55e1be-339d-4276-ac3e-04a39891ad7d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("15475ee9-da71-4162-9b74-6ab2827621ad"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
