# Generated by Django 5.0.4 on 2024-04-17 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fd933485-24e0-416c-b515-3d117a49e268"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("56f9a85d-28d5-4c7a-a984-85322b1f85b2"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2932eef4-70a8-4df9-a77e-3e32f2b61aa3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
