# Generated by Django 5.0.4 on 2024-04-16 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8f33d768-9042-46fb-ab63-16bb2c9e6cdd"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("12eae6ff-27d1-4ffe-a948-155bc9784c29"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("287e94de-1223-411e-9956-d947dd6151d5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
