# Generated by Django 5.0.4 on 2024-04-17 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("103d8132-bfd2-42be-8a3b-489974701302"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e6ae256d-b656-4a00-a721-1d431cd2e21e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d5bbcea3-3b36-4edd-be66-2f3a1e6976f9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
