# Generated by Django 5.0.4 on 2024-04-17 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b2de2f7b-35ab-4896-b23e-6e6b304f3728"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("00fe9216-c3e5-4cc7-af6c-099abbff1f0a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ad9c17a7-3c4f-4a72-b75d-f04ddecb6586"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
