# Generated by Django 5.0.4 on 2024-04-17 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3bb3b2ec-37c7-4467-af69-befaf955670d"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("57312b5c-0ee5-4ef8-b0b9-fba74f3d14c6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("95138679-b172-42b3-ab35-4e1fb586d882"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
