# Generated by Django 5.0.4 on 2024-04-17 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_is_seller_user_is_superuser_alter_address_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2d04df1e-a834-4ece-b423-1f2a7ca5b164"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("17866b5b-cbbb-418f-9d8a-58b5020cbf93"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("16d1ff2d-3958-4195-aaa1-59260e82d000"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
