# Generated by Django 5.0.4 on 2024-04-17 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9a6e8c65-b63f-421d-8b93-a41ad1e2258e"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b50751f2-bd6a-49ab-96b7-283270affe7e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4fb0e37c-001b-4fb9-a695-7be12d30027a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
