# Generated by Django 5.0.4 on 2024-04-20 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9a1ca958-40b1-4909-9865-10fa2e16c838"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8c45de02-5f72-4ff9-b277-a42e48e1ab67"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7268f99c-d9bd-44b7-b5ed-07c3ae3ec762"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
