# Generated by Django 5.0.4 on 2024-04-21 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a2aee46d-a420-4b6f-b1ef-d4a7d6236110"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1c506b45-5480-4e9f-be93-04c5a6535b07"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ff951e7f-58b8-4d49-8df6-56a344e478b4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
