# Generated by Django 5.0.4 on 2024-04-21 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_address_id_alter_buyer_id_alter_sellers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0d9a1373-226e-4709-9ae9-1c536ec93754"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1c42147d-f822-431e-9972-93d4ee204f23"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sellers",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5d08e9ca-2b57-4e70-b1b8-3894aa0a8dd9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
