# Generated by Django 5.0.4 on 2024-05-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_category"),
        ("shop", "0004_alter_rating_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="products.product",
            ),
        ),
    ]
